#! /bin/bash

scp -i ~/Downloads/laessig-training.pem aufgabe1zip.zip ec2-user@3.123.128.188:/home/ec2-user/

ssh ec2-user@3.123.128.188 -i ~/Downloads/laessig-training.pem << 'ENDSSH'

mkdir -p siher

cp ./aufgabe1zip.zip ./siher

cd ~/siher

unzip aufgabe1zip.zip 

rm aufgabe1zip.zip 

ENDSSH





